#if !defined(ASYNCIO_WIN32_SELECTOR_EPOLL) && !defined(ASYNCIO_WIN32_SELECTOR_WSAPOLL)
#define _ASYNCIO_WIN32_SELECTOR_EPOLL
#else
#if defined(ASYNCIO_WIN32_SELECTOR_EPOLL)
#define _ASYNCIO_WIN32_SELECTOR_EPOLL
#else
#define _ASYNCIO_WIN32_SELECTOR_WSAPOLL
#endif // ASYNCIO_WIN32_SELECTOR_EPOLL
#endif // !ASYNCIO_WIN32_SELECTOR_EPOLL && !ASYNCIO_WIN32_SELECTOR_WSAPOLL

